
import { Client, AppSettings, PaymentMethod } from './types';

export const INITIAL_CLIENTS: Client[] = [];

export const ALL_AVAILABLE_ACCOUNTS: PaymentMethod[] = [
  'Super M-pesa',
  'Super E-mola',
  'M-pesa',
  'E-mola',
  'Cash'
];

export const INITIAL_SETTINGS: AppSettings = {
  appName: 'Super Agente MNG NICE', 
  currency: 'Mts', 
  language: 'pt', 
  theme: 'dark',
  enabledAccounts: ['Super M-pesa', 'Super E-mola', 'M-pesa', 'E-mola', 'Cash'],
  accountColors: {
    'Super M-pesa': '#3b82f6',
    'Super E-mola': '#f43f5e',
    'M-pesa': '#f59e0b',
    'E-mola': '#10b981',
    'Cash': '#6366f1'
  },
  uiConfig: {
    primaryColor: '#3b82f6',
    transparency: 0.2 // 80% transparência significa 20% opacidade do fundo colorido
  },
  smsTemplates: { 
    confirmation: "Super Agente MNG NICE: Confirmamos a saída de {amount} {currency} em sua conta. Referência: {desc}", 
    debtReminder: "Lembrete: Tens um saldo em dívida de {amount} {currency}. Favor regularizar." 
  }
};

export const translations = {
  pt: {
    login_subtitle: "Gestão Financeira para Agentes em Moçambique",
    login_name: "Nome Completo",
    login_phone: "Telefone",
    login_pass: "Senha",
    login_btn_create: "Criar Conta",
    login_btn_signin: "Entrar",
    login_forgot: "Esqueceu a Senha?",
    login_recover_title: "Recuperar Conta",
    login_recover_desc: "Confirme o número para definir nova senha",
    login_recover_verify: "Verificar Número",
    login_recover_set: "Definir Nova Senha",
    nav_home: "Início",
    nav_clients: "Clientes",
    nav_settings: "Ajustes",
    dash_greeting: "Bom dia",
    dash_chart_title: "Agregado Total (7 Dias)",
    dash_recent: "Atividade Recente",
    client_search: "Pesquisar clientes...",
    client_new: "Novo Cliente",
    client_balance_label: "Saldo Atual",
    client_close: "Fechar Conta",
    client_active_ledger: "Extrato Activo",
    client_archive_title: "Arquivo de Contas",
    client_debt: "Saldo Devido",
    client_liquidated: "Liquidado",
    client_pending: "Pendente",
    tx_inflow: "Entrada (Crédito)",
    tx_outflow: "Saída (Débito)",
    tx_amount: "Valor",
    tx_method: "Método",
    tx_date: "Data",
    tx_desc: "Descrição",
    tx_cancel: "Cancelar",
    tx_confirm: "Confirmar",
    settings_title: "Ajustes",
    settings_appearance: "Aparência",
    settings_darkmode: "Modo Escuro",
    settings_language: "Idioma",
    settings_user_profile: "Usuário",
    settings_accounts: "Contas Ativas",
    settings_localization: "Localização",
    settings_currency: "Moeda Padrão",
    settings_sms: "Configuração de SMS",
    settings_logout: "Sair da Conta",
    settings_edit: "Editar Dados",
    settings_pass: "Alterar Senha",
    settings_acc_balance: "Saldo",
    modal_save: "Salvar",
    archive_empty: "Sem contas arquivadas",
    archive_date: "Encerrada em",
    app_name_label: "Nome do Aplicativo",
    sms_confirm_prompt: "Deseja enviar mensagem de confirmação?",
    sms_confirm_btn: "Enviar SMS",
    client_edit: "Editar Cliente",
    ui_customization: "Personalização Visual",
    ui_primary_color: "Cor Principal",
    ui_transparency: "Transparência do Fundo",
    confirm_delete: "Tem certeza que deseja excluir permanentemente?",
    delete_client: "Excluir Cliente"
  },
  en: {
    login_subtitle: "Financial Management for Mozambique Agents",
    login_name: "Full Name",
    login_phone: "Phone Number",
    login_pass: "Password",
    login_btn_create: "Create Account",
    login_btn_signin: "Sign In",
    login_forgot: "Forgot Password?",
    login_recover_title: "Recover Account",
    login_recover_desc: "Verify number to set new password",
    login_recover_verify: "Verify Number",
    login_recover_set: "Set New Password",
    nav_home: "Home",
    nav_clients: "Clients",
    nav_settings: "Settings",
    dash_greeting: "Good Morning",
    dash_chart_title: "Total Aggregate (7 Days)",
    dash_recent: "Recent Activity",
    client_search: "Search clients...",
    client_new: "New Client",
    client_balance_label: "Current Balance",
    client_close: "Close Account",
    client_active_ledger: "Active Ledger",
    client_archive_title: "Account Archive",
    client_debt: "Balance Due",
    client_liquidated: "Settled",
    client_pending: "Pending",
    tx_inflow: "Inflow (Credit)",
    tx_outflow: "Outflow (Debit)",
    tx_amount: "Amount",
    tx_method: "Method",
    tx_date: "Date",
    tx_desc: "Description",
    tx_cancel: "Cancel",
    tx_confirm: "Confirm",
    settings_title: "Settings",
    settings_appearance: "Appearance",
    settings_darkmode: "Dark Mode",
    settings_language: "Language",
    settings_user_profile: "User",
    settings_accounts: "Active Accounts",
    settings_localization: "Localization",
    settings_currency: "Default Currency",
    settings_sms: "SMS Settings",
    settings_logout: "Logout",
    settings_edit: "Edit Info",
    settings_pass: "Change Password",
    settings_acc_balance: "Balance",
    modal_save: "Save",
    archive_empty: "No archived accounts",
    archive_date: "Closed on",
    app_name_label: "App Name",
    sms_confirm_prompt: "Send confirmation message?",
    sms_confirm_btn: "Send SMS",
    client_edit: "Edit Client",
    ui_customization: "Visual Customization",
    ui_primary_color: "Primary Color",
    ui_transparency: "Background Transparency",
    confirm_delete: "Are you sure you want to delete permanently?",
    delete_client: "Delete Client"
  }
};
